local status = require("src.reporting.status")
local Reporting = require("src.reporting.safe")
local Statistics = require("src.reporting.statistics")

assert(status.phase("MAIN", 5, 20, "step 2/3") == "[MAIN] 5/20 step 2/3")
assert(status.phase("BRANCH", 17, 20, "L out") == "[BRANCH] 17/20 L out")
assert(status.branchComplete(5, 20, 123, 456) == "[DONE] pair 5/20 B:123 F:456")
assert(#status.phase("A_VERY_LONG_PHASE_NAME", 123456, 987654, "a very long detail") <= 32)
assert(#status.branchComplete(123456, 987654, 123456789, "unlimited") <= 32)
assert(not Reporting.log(function() error("sink failed") end, "status"))
assert(Reporting.log(function(value) assert(value == "status") end, "status"))

local stats = Statistics.new({ blocks_mined = 0 })
assert(stats:add("blocks_mined", 2))
assert(stats:get("blocks_mined") == 2)
assert(stats:add("blocks_mined", "invalid"))
assert(stats:get("blocks_mined") == 2)
assert(stats:add("ores_mined", 3))
assert(stats:add("fuel_used", 6))
assert(stats:add("branches_completed", 2))
assert(stats:add("tunnel_blocks_mined", 12))
assert(Statistics.addOreCounts(stats, { name = "mod:iron_ore" }, 2))
local summary = Statistics.jobSummary(stats, { startedAt = 10, endedAt = 3610 })
assert(summary.blocksDug == 2)
assert(summary.oreBlocksDug == 3)
assert(summary.orePerFuel == 0.5)
assert(summary.orePerTunnel == 0.25)
assert(summary.orePerActiveHour == 3)
assert(summary.branchPairsCompleted == 2)
assert(summary.oreByType["ore_type:mod:iron_ore"] == 2)
assert(Statistics.addOreCounts(stats, { name = "mod:iron_ore" }, 1))
assert(stats:get("ore_type:mod:iron_ore") == 3)
assert(#Statistics.formatJobSummary(summary) == 4)
local emptySummary = Statistics.jobSummary(Statistics.new(), { startedAt = 10, endedAt = 10 })
assert(emptySummary.orePerFuel == 0 and emptySummary.orePerActiveHour == 0)

print("status reporting tests passed")
